### ISSUE TITLE
Cannot import MLS

### ISSUE THREAD

**Issue by Chris56** [Helium314/Local-NLP-Backend#10]
1.2.4 from f-droid:
I downloaded Mozillas full cell exports csv file from here: https://location.services.mozilla.com/downloads
The import skips every entry.

**Comment by Helium314** [comment]
You're right, this happens when no MCC filter is set, despite the text saying "Leave blank to import all".
Will be fixed in the next version.

**Comment by Chris56** [comment]
As you seem to be working on it, one idea:
Perhaps it is possible to offer the possibility to only stating the initial digit.
Like in my case: I will be travelling around Europe, thus I would like to import all 2xx countries.

**Comment by Helium314** [comment]
I added this now, so every `x` will count for 0-9.
Though it might get removed later...  the UI could really use an upgrade, and then the MCC selection then may be replaced by a country selector, similar to the local GSM backend. (if I ever find time for this)

> Is there a way to tell which of several the microg backends produces which result?

You can use logcat and filter for [`LocationFuser`](https://github.com/microg/UnifiedNlp/blob/master/service/src/main/kotlin/org/microg/nlp/service/LocationFuser.kt#L98-L114), but this does not provide any information if a location is "older than other provider".

**Comment by Chris56** [comment]
In case the UI switches to countries, I would propose to also offer Europe (all of), Asia and so on. That will be the equivalent to ?xx MCC filter.
Thanks for you work!
