### ISSUE TITLE
microG remove NLP module support since 0.2.28.231657

### ISSUE THREAD

**Issue by CoelacanthusHex** [Helium314/Local-NLP-Backend#18]
Upstream microG remove NLP module support since 0.2.28.231657, and only use builtin module. So we can't use this project with microG.
Upstream still doesn't provide new module way. But they said, "No modules anymore, they became unreliable in recent Android versions due to 'energy savings'"
If upstream don't want to support external module because of background control of newer androids, the only way may be try to merge this project into microG project.

**Comment by Helium314** [comment]
Let's see how the microG issue to merge it works out. From my side this would be fine, as long as it's not necessary to completely overhaul the internal structure.

Personally I only use microG for the NLP component and have everything else disabled.
So for myself I could stay on ancient microG version 2.10 (with later versions I have issues where location requests sometimes don't arrive at Local NLP Backend)

**Comment by Iey4iej3** [comment]
If I understand correctly, it is saying that NLP does not work (or not reliably) on latest Android (maybe Android ≥13?) due to some sort of new battery saving machinery, and that is why they removed this feature.

**Comment by Helium314** [comment]
microG has already added some basic Local NLP backend functionality: https://github.com/microg/GmsCore/issues/1941#issuecomment-1656590182
So I think there is nothing that can be done here, and I'll close the issue.

However, due to relevance it will be pinned.

**Comment by mutageneral** [comment]
Any way to open the Local NLP Backend app externally? Now that F-Droid auto updated me to the latest version of microG, I can't use microG to open Local NLP Backend to export the data to import it into the new microG built in one. I can't downgrade microG either. Catch-22.

**Comment by Helium314** [comment]
Did you install Local NLP Backend from F-Droid?

**Comment by mutageneral** [comment]
Yes, I have it from F-Droid. It worked well.
The problem I have is that you can't open the Local NLP Backend settings directly from an icon in my launcher or something, you explicitly have to use the old version of microG that still has NLP settings to open Local NLP Backend. The old version of microG that still has NLP setting is now gone forever from my phone. So exporting data from Local NLP Backend is now inaccessible.
The only way to fix this I can see would be to update Local NLP Backend to let it be opened from my launcher, if that's even possible.

**Comment by dazzzl** [comment]
I have the same problem. Update from Lineageos for MicroG 21 -> 22.1. I still have my rf.db from the app data location. I am not sure anymore if the export function  was only write the sqlite3 db or a csv file. What does the new network location from MicroG needs as an import format? I tried to give them the rf.db, but I think this was not working (no response from the appI

**Comment by dazzzl** [comment]
So, I have seen that the new location backend needs a different database scheme ... see here:
https://github.com/microg/GmsCore/commit/44a9a4dfa4aac5e284875d4cd82f9e25ca84baa1

Has someone already wrote a converter script?

**Comment by dazzzl** [comment]
https://github.com/microg/GmsCore/issues/2771
