### ISSUE TITLE
import data error

### ISSUE THREAD

**Issue by Nichtraucher** [Helium314/Local-NLP-Backend#20]
Hey :-)

Previously, I've used Déjà Vu NLP -> I disabled it -> installed "Local NLP Backend" -> import data -> selected a csv file from opencellid -> "keep local emitters unchanged" ->  error message: "error: file format unknown". I also tried it with the original, compressed .gz-file - to no avail.

Did I do anything wrong?

cheers

**Comment by Helium314** [comment]
The import expects the first line of the csv to be `radio,mcc,net,area,cell,unit,lon,lat,range,samples,changeable,created,updated,averageSignal`, which to my knowledge is the case for MLS and OpenCelliD (may be outdated though).
Is it the same in your file?

**Comment by Nichtraucher** [comment]
The file is too large to be processed by a spreadsheet program. I opened it in a text editor and didn't see them on the top. I tried to search for these words within the file, but again, that didn't work because of the size.  I can't tell, sorry!  :-(

**Comment by Helium314** [comment]
The line needs to first, otherwise it will not work.
Though maybe the requirement for the line could be removed, and Local NLP could instead try to parse the first line to identify file type...

**Comment by Nichtraucher** [comment]
> may be outdated though

That seems to be the case. I checked the dataset from the mozilla database and it doesn't include the titles for the parameters either.

**Comment by Helium314** [comment]
Import without the header should work in the next version.

**Comment by Nichtraucher** [comment]
It does work, thank you!
