### ISSUE TITLE
import errror for opencellid csv

### ISSUE THREAD

**Issue by andidevi** [Helium314/Local-NLP-Backend#28]
Thanks for this backend! I'm using it together with LineageOS 21 (Android 14) together with UnifiedNLP (w/gapps) and avbroot.

When trying to import some freshly downloaded csv from opencellid this failes for all files with Error: file format unknown.
Regarding to #20 this should work.
One example:
[cz_230.csv](https://github.com/user-attachments/files/17600138/cz_230.csv)

Adding the headers from https://github.com/Helium314/Local-NLP-Backend/issues/20#issuecomment-1676118018
did remove the  error message but export after import was empty.

Maybe file format of opencellid downloads has changed, but I don't have a known working download at hand.

**Comment by Helium314** [comment]
The problem was rather simple, and a result of a wrong list element checked in another fix: https://github.com/Helium314/Local-NLP-Backend/commit/773c25c34a4725dfd8c54d8fd9bffc377f902c42
