### ISSUE TITLE
Déjà Vu database import: 'Error: file format unknown'

### ISSUE THREAD

**Issue by sylph1o** [Helium314/Local-NLP-Backend#3]
Hi!

I had been using the Déjà Vu NLP backend until now and wished to import its database into Local NLP. The description of the 'Import data' option in the interface of Local NLP suggests that this is supported. However, the import fails with the message 'Error: file format unknown'.

Steps to reproduce
1. Copy `/data/data/org.fitchfamily.android.dejavu/databases/rf.db` to a location accessible without root privileges.
2. Open the configuration interface of Local NLP backend
3. Select 'Import data'
4. Select the file `rf.db` copied at step 1.
5. Pick any option on how to handle emitters already existing in the local database, it makes no difference.
6. Observe error message.

Is this import not supported? If it is, does anyone has ny idea as to the cause of the problem, or a possible solution?

**Comment by Helium314** [comment]
Actually this is supposed to work...
Which version are you using? There were some changes in the related code between the first beta and the current beta 3.

**Comment by sylph1o** [comment]
Sorry, I should have included that information.
- Local NLP backend: version 1.2.0-beta.3 (F-Droid build)
- Déjà Vu NLP backend: version 1.1.12 (F-Droid build)

**Comment by Helium314** [comment]
Actually I just tested, and couldn't reproduce the issue in any of those versions...

Is your file really named _rf.db_?
When, importing, only files ending with _.db_ are loaded as database. All other endings are interpreted as text files... and it appears the file ending check fails in your case.

**Comment by sylph1o** [comment]
> Is your file really named rf.db?

Yes, it is. Perhaps the file is somehow corrupted. [Here it is](https://transfer.sh/8rxpMc/rf.db). Can you reproduce the issue with this file?

**Comment by Helium314** [comment]
This is weird.... it works perfectly fine for me.
I suspect your phone may not report the real file name when importing.
Could you try with this [APK](https://github.com/Helium314/Local-NLP-Backend/files/9543437/local-nlp-backend_1.2.0-beta.3-release_error_detail.zip)?

It's exactly the same as beta 3, but the error message will contain the full file path.
Is there _rf.db_ at the end if you try it?

**Comment by Helium314** [comment]
Ok, maybe you don't need to try, I just found some issue with my method of determining the file name.

**Comment by Helium314** [comment]
Could you check whether the import works with this: [local-nlp-backend_1.2.0-beta.3-release_import_fix_attempt.zip](https://github.com/Helium314/Local-NLP-Backend/files/9543482/local-nlp-backend_1.2.0-beta.3-release_import_fix_attempt.zip)

**Comment by sylph1o** [comment]
This last APK seems to be able to import my `rf.db` file:
- instead of the error message, the notification shows a progress counter ('X/Y' with X going from 0 to Y), followed by 'Import finished';
- exporting the resulting database of the Local NLP backend as CSV yields a large file with many entries (approximately Y entries) which look correct to me (i.e. I recognise some of these entries).

As far as I am concerned, this perfectly solves the issue :slightly_smiling_face:  . Thank you for being so responsive!

**Comment by Helium314** [comment]
No need for further testing, thanks!
